### ISSUE TITLE
API 5.0

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2180]
I started dividing the long list of changes into small work packages, which can be tackled one by one. Went until `file albums` for now. feel free to edit & extend the list.

If we work on this with multiple people, I propose making a `api-5.0-master` branch which we can feed the changes to one by one in standalone PRs so that we have small PRs to review and at the same time have one big PR for checking that `test_official` works out before we merge 

**Edit:** See #2181. all api-5.0-PRs should be based on `api-5.0-master`. If merge conflicts occour with master, we can merge once in the end.

- [x] **WP1: API Servers** (@Bibo-Joshi, #2183)
new `logOut` and `close` methods

- [x] **WP2.1: Webhooks** (@Bibo-Joshi, #2183)
new parameters for `set/deleteWebhook`

- [x] **WP2.2: Webhooks** (@Bibo-Joshi, #2183)
  * New attribute for `WebhookInfo`

- [x] **WP3.1: Groups** (@Bibo-Joshi, #2185)
new attributes for `Chat`, returned by `get_chat`

- [x] **WP3.2: Groups** (@Bibo-Joshi, #2185)
  * new class `ChatLocation`
  * new parameter for `unban_chat_member`

- [x] **WP4.1: Files** (@Bibo-Joshi, #2186 )
new attribute for `Audio` and `Video`

- [x] **WP4.2: Files** (@Bibo-Joshi, #2186 )
new parameter for `send_document` and `InputMediaDocument`

- [ ] **WP4.3: Files** (@Poolitzer, #2223)
check how the custom bot API server behaves with the local flag and file download

- [ ] **WP4.4: Files** (#2223)
for self hosted servers with the local flag, files can be passed as `file:///absolute/path/to/file`. Maybe not in the initial release of api 5.0 but at least in the long rung we should support
  * passing only `/absolute/path/to/file`
  * passing only `/relative/path/to/file`
  * maybe even passing a `pathlib.Path` object

- [x] **WP5: Pinned messages** (@harshil21, #2184 )
  * new parameter for `unpit_chat_message`
  * new method `unpit_all_chat_messages`

- [x] **WP6: File albums** (#2187)
update type hints for `send_media_group`

- [x] **WP7.1: Live Locations** (@Bibo-Joshi, #2188)
  * new attribute `live_period` for `Location`
  * new class `ProximityAlertTriggered`
  * new attribute `proximity_alert_triggered` for `Message`

- [x] **WP7.2: Live Locations** (@Bibo-Joshi, #2188)
new attributes `heading`, `proximity_alert_distance` and `horizontal_accuracy` for `Location`, `InlineQueryResultLocation` and `InputLocationMessageContent`.

- [x] **WP7.3: Live Locations** (@Bibo-Joshi, #2188)
new parameters `heading`, `proximity_alert_distance` and `horizontal_accuracy` for `send_location` and `edit_message_live_location`.

- [x] **WP8.1: Anonymous Admins** (@Bibo-Joshi, #2189)
  * new attribute `sender_chat` for `Message`
  * ~depricate~ remove the recently added convenience properties (see #2147, that never was in a release, so we might as well remove completely)

- [x] **WP8.2: Anonymous Admins** (@Bibo-Joshi, #2189)
  * new attribute `is_anonymous` for `ChatMember`
  * new parameter `is_anonymous` for `promote_chat_member`
  * update docstring of `Message.author_signature`

- [x] **WP9.1: And More** (@Poolitzer, #2196 )
  * new class `MessageID`
  * new method `copy_message`
  * check if we have a constant for maximum poll question length. if yes, update, if no add

- [ ] **WP9.2: And More - Entities** (@Bibo-Joshi, #2199)
new parameter `entities` for the `InputMedia` classes

- [ ] **WP9.3 And More - Entities** (@Bibo-Joshi, #2199)
new parameter `entities` for the `InlineQueryResult` classes

- [ ] **WP9.4: And More - Entities** (@Bibo-Joshi, #2199)
new parameter `entities` for the `send_{message,photo,video,animation,audio,document,voice,poll}` and `edit_message_{text,caption}` methods

- [ ] **WP9.5: And More** (@Bibo-Joshi, #2193)
  * new google place attributes for `Venue`, `IQRVenue`, `InputVenueMessageContent`
  * new google api attributes parameters for `send_venue`

- [x] **WP9.6: And More** (@Bibo-Joshi, #2192)
  * new parameter `allow_sending_without_reply` to all the `send_*` methods
  * add as Default

- [x] **WP10: Dice** (@Bibo-Joshi, #2190)
  * Add football and slot machine to `Dice`
  * Add corresponding filters

- [ ] **WP11.1: Meta**
  * double check that test_official is happy
  * double check that all the docs were updated correctly

- [ ] **WP11.2: Meta**
double check everything once more

- [x] **WP12: Shortcuts (@Poolitzer, #2196 )**
this would be nice to have in the 5.0 PR but if not, that's okay too, then we'll do later
  * `Message.reply_copy` as shortcut for `copy_message(chat_id=message.chat_id, …)`
  * `Message.copy` as shortcut for `copy_message(from_chat_id=message.chat.id, message_id=message.message_id, …)`
  * `CallbackQuery.copy_message` as shortcut for `cbq.message.copy`
  * `{Chat, User}.copy_message` as shortcut for `copy_message(from_chat_id=chat/user.id, …)`
  * `{Chat, User}.send_copy` as shortcut for`copy_message(chat_id=chat/user.id, …)`

- [x] **WP13: New things building on API 5.0** (#2205)
these can go into separate PRs and don't necessarily have to be released with API 5.0. just noting here before I forget:
  * use the self-hosted api servers to stabilize tests.
  * `Filters.sender_chat` working the same as `Filters.chat`. Calling `Filters.sender_chat(chat_id)` will allow to exclude anon. admins and forwarded channel posts in _specific_  groups. Also by now it's probably good to have `Filters.{chat, user, via_bot, sender_chat}` inherit from a common base class or from one another …
  * adding attributes `Filters.sender_chat.{super_group, channel}` will allow to exclude anon. admins and forwarded channel posts in _all_ groups

- [x] **WP14: New Wiki page**
create a wiki page listing common questions for self-hosted apis. this should include
  * a note about the `--local` flag and files
  * a note that the `base_url` should end with `/bot`

**Comment by harshil21** [comment]
If it's okay, I'd like to work on the new pinned messages update once the `api-5.0-master` branch is made

**Comment by Bibo-Joshi** [comment]
> If it's okay, I'd like to work on the new pinned messages update once the `api-5.0-master` branch is made

Ofc, you're welcome to :D I "assigned" you by putting your name behind the WP. (actually assigning people on this issue will be of little help …)

**Comment by Poolitzer** [comment]
I am going to do copy message now
