### ISSUE TITLE
[FEATURE] API 7.3

### ISSUE THREAD

**Issue by clot27** [python-telegram-bot/python-telegram-bot#4236]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

New update :D

### Important

- Comment here or in the dev group what you want to work on so we can assign you
- Please copy the relevant part of the checklist from
- https://github.com/python-telegram-bot/python-telegram-bot/issues/4236 to your PR and make sure to cover everything :)
- Please base your branch on the [api-7.3-central](https://github.com/python-telegram-bot/python-telegram-bot/tree/api-7.3-central) branch
- If this is your first contribution, please be sure to read the [contribution guide](https://docs.python-telegram-bot.org/en/v20.7/contributing.html) and feel free to reach out with any questions via https://t.me/pythontelegrambotchannel/105

### Describe the solution you'd like

- [x] Added support for [InlineKeyboardMarkup](https://core.telegram.org/bots/api#inlinekeyboardmarkup) with url, login_url, and callback_game buttons for messages sent on behalf of a business account. @Bibo-Joshi #4246
- [x]     Added the field via_join_request to the class [ChatMemberUpdated](https://core.telegram.org/bots/api#chatmemberupdated) - Taken by @aelkheir. #4247
- [x]     Added support for live locations that can be edited indefinitely, allowing 0x7FFFFFFF to be used as live_period. @Bibo-Joshi  #4246
- [x]     Added the parameter live_period to the method [editMessageLiveLocation](https://core.telegram.org/bots/api#editmessagelivelocation) - Taken by @aelkheir. #4247 
- [x]     Added the field question_entities to the class [Poll](https://core.telegram.org/bots/api#poll) - Taken by @aelkheir. #4260
- [x]     Added the field text_entities to the class [PollOption](https://core.telegram.org/bots/api#polloption) - Taken by @aelkheir. #4260
- [x]     Added the parameters question_parse_mode and question_entities to the method [sendPoll](https://core.telegram.org/bots/api#sendpoll) - Taken by @aelkheir.
- [x]     Added the class [InputPollOption](https://core.telegram.org/bots/api#inputpolloption) and changed the type of the parameter options in the method [sendPoll](https://core.telegram.org/bots/api#sendpoll) to Array of [InputPollOption](https://core.telegram.org/bots/api#inputpolloption) - Taken by @Bibo-Joshi #4248
- [x]     Added the classes [ChatBackground](https://core.telegram.org/bots/api#chatbackground), [BackgroundType](https://core.telegram.org/bots/api#backgroundtype), [BackgroundFill](https://core.telegram.org/bots/api#backgroundfill) and the field chat_background_set of type [ChatBackground](https://core.telegram.org/bots/api#chatbackground) to the class [Message](https://core.telegram.org/bots/api#message), describing service messages about background changes - Taken by @aelkheir. #4247
- [x]     Split out the class [ChatFullInfo](https://core.telegram.org/bots/api#chatfullinfo) from the class [Chat](https://core.telegram.org/bots/api#chat) and changed the return type of the method [getChat](https://core.telegram.org/bots/api#getchat) to [ChatFullInfo](https://core.telegram.org/bots/api#chatfullinfo) - Taken by @harshil21. #4242
- [x]     Added the field max_reaction_count to the class [ChatFullInfo](https://core.telegram.org/bots/api#chatfullinfo) - Taken by @harshil21. #4242
- [x]     Documented that .MP3 and .M4A files can be used as voice messages. @Bibo-Joshi #4246

### Describe alternatives you've considered

If you want to contribute, you can start from the [Contribution Guide](https://docs.python-telegram-bot.org/en/v20.7/contributing.html).

### Additional context

Please comment below before start working on any part of the update to keep things in track and avoid double work.

**Comment by aelkheir** [comment]
Hi! would like to do these

- [ ] Added the field via_join_request to the class ChatMemberUpdated.
- [ ] Added the parameter live_period to the method editMessageLiveLocation.
- [ ] Added the field question_entities to the class Poll.
- [ ] Added the field text_entities to the class PollOption.
- [ ] Added the parameters question_parse_mode and question_entities to the method sendPoll.
- [ ] Added the class InputPollOption and changed the type of the parameter options in the method sendPoll to Array of InputPollOption.
- [ ] Added the classes ChatBackground, BackgroundType, BackgroundFill and the field chat_background_set of type ChatBackground to the class Message, describing service messages about background changes.

**Comment by harshil21** [comment]
@aelkheir Okay! Assigning you.

**Comment by harshil21** [comment]
I'll work on the `ChatFullInfo` class.
