### ISSUE TITLE
Test suite maintainence and new ideas

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#4324]
Our test suite has once again degraded in performance and flakiness has been reintroduced. We can experiment / make our test suite better in different ways, some of my current ideas are listed roughly below:

- [x] Try to make everything as concurrent as possible (#4271)
- [ ] Profile all tests and see what clogs up and fix that.
- [ ] solve the TODO in `test_official.exceptions`
- [ ] #4514
- [ ] [`dirty-equals`](https://dirty-equals.helpmanual.io/latest/) sounds like it could be quite useful for us!
- [x] Think about renaming the `Test*Base` classes to just `*Base` since pytest collects the classes starting with `Test*`. #4453
- [x] Change CI's pytest  `--dist` to `worksteal` #4491 .
- [x] Extend that naming scheme to `telegram.ext` tests
- [x] fix the class name https://github.com/python-telegram-bot/python-telegram-bot/blob/51ef571a0761bbfea136c455bbfa67d47b20585c/tests/test_menubutton.py#L94 #4453

Follow https://github.com/zupo/awesome-pytest-speedup, not all items but some are worth looking at:

- [x] Introduce `pytest-socket` and completely disable network access for `*WithoutRequest` tests (#4317, #4454)
- [x] ~Introduce `pyfakefs` to test suite~ (no major benefit found - https://github.com/python-telegram-bot/python-telegram-bot/pull/4271#issuecomment-2127968133)
- [ ] Check if using `uvloop` in tests provides any measurable speed up.
- [ ] Isolate tests from other tests
- [ ] Check if introducing `pytest-randomly` (need to check if pytest-xdist effectively does the job of randomly)

-> Check if using `pytest-asyncio-cooperative` is worth it
     - Nope it is not.

**Comment by MrLightspeed** [comment]
@codex review
