### ISSUE TITLE
[FEATURE] API 7.11

### ISSUE THREAD

**Issue by aelkheir** [python-telegram-bot/python-telegram-bot#4543]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

API 7.11

> [!IMPORTANT]  
> - Comment here or in the dev group what you want to work on so we can assign you
> - Please copy the relevant part of the checklist from #4543 to your PR and make sure to cover everything :)
> - Please base your branch on the [api-7.11](https://github.com/python-telegram-bot/python-telegram-bot/tree/api-7.11)branch
> - If this is your first contribution, please be sure to read the [contribution guide](https://docs.python-telegram-bot.org/en/v20.7/contributing.html) and feel free to reach out with any questions via https://t.me/pythontelegrambotchannel/105

### Describe the solution you'd like

- [x] Added the class [CopyTextButton](https://core.telegram.org/bots/api#copytextbutton) and the field copy_text in the class [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardbutton) allowing bots to send and receive inline buttons that copy arbitrary text. @Bibo-Joshi #4547
- [x] Added the parameter allow_paid_broadcast to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendPaidMedia](https://core.telegram.org/bots/api#sendpaidmedia), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendInvoice](https://core.telegram.org/bots/api#sendinvoice), [sendGame](https://core.telegram.org/bots/api#sendgame), [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup) and [copyMessage](https://core.telegram.org/bots/api#copymessage). @Bibo-Joshi  #4550
- [x] Added the class [TransactionPartnerTelegramApi](https://core.telegram.org/bots/api#transactionpartnertelegramapi) for transactions related to paid broadcasted messages. @Bibo-Joshi #4548
- [x] Introduced the ability to add media to existing text messages using the method [editMessageMedia](https://core.telegram.org/bots/api#editmessagemedia). #4546
- [x] Added support for hashtag and cashtag [entities](https://core.telegram.org/bots/api#messageentity) with a specified chat username that opens a search for the relevant tag within the specified chat. @Bibo-Joshi 4546

### Describe alternatives you've considered

If you want to contribute, you can start from the [Contribution Guide](https://docs.python-telegram-bot.org/en/v20.7/contributing.html).

### Additional context

Please comment below before start working on any part of the update so as to keep things in track and avoid double work.
