### ISSUE TITLE
Bot API 8.0

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#4567]
>[!Important]
> 
> - Comment here or in the dev group what you want to work on so we can assign you
> - Please copy the relevant part of the checklist from https://docs.python-telegram-bot.org/en/v21.7/contributing.html#check-list-for-prs to your PR and make sure to cover everything :)
> - Please base your branch on the [api-8.0](https://github.com/python-telegram-bot/python-telegram-bot/tree/api-8.0) branch
> - If this is your first contribution, please be sure to read the [contribution guide](https://docs.python-telegram-bot.org/en/latest/contributing.html) and feel free to reach out with any questions via https://t.me/pythontelegrambotdev

### Bot API 8.0

> Bot API 8.0 introduces 10 powerful new features for Mini Apps - including the ability to enter [full-screen mode](https://telegram.org/blog/fullscreen-miniapps-and-more#full-screen-mode), launch from [home screen shortcuts](https://telegram.org/blog/fullscreen-miniapps-and-more#home-screen-shortcuts), offer [subscription plans](https://telegram.org/blog/fullscreen-miniapps-and-more#subscription-plans) and more. Check out all the details in our dedicated [blog](https://telegram.org/blog/fullscreen-miniapps-and-more) and Mini App [documentation](https://core.telegram.org/bots/webapps).

#### Star Subscriptions

- [x] Bots now support paid subscriptions powered by [Telegram Stars](https://telegram.org/blog/telegram-stars) - monetizing their efforts with multiple tiers of content and features.
- [ ] Added the parameter subscription_period to the method [createInvoiceLink](https://core.telegram.org/bots/api#createinvoicelink) to support the creation of links that are billed periodically. @Bibo-Joshi #4568
- [ ] Added the parameter business_connection_id to the method [createInvoiceLink](https://core.telegram.org/bots/api#createinvoicelink) to support the creation of invoice links on behalf of business accounts. @Bibo-Joshi #4568
- [ ] Added the fields subscription_expiration_date, is_recurring and is_first_recurring to the class [SuccessfulPayment](https://core.telegram.org/bots/api#successfulpayment). #4570 
- [ ] Added the method [editUserStarSubscription](https://core.telegram.org/bots/api#edituserstarsubscription). #4571
- [ ] Added the field subscription_period to the class [TransactionPartnerUser](https://core.telegram.org/bots/api#transactionpartneruser).  @Bibo-Joshi #4576

#### Full-screen Mode

- [x] Mini Apps are now able to [become full-screen](https://telegram.org/blog/fullscreen-miniapps-and-more#full-screen-mode) in both portrait and landscape mode - allowing them to host more games, play widescreen media and support immersive user experiences.
- [x] Added the methods requestFullscreen and exitFullscreen to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps) to toggle full-screen mode.
- [x] Added the fields safeAreaInset and contentSafeAreaInset to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps), allowing Mini Apps to ensure that their content properly respects the device's safe area margins.
- [x] Further added the fields isActive and isFullscreen to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).
Added the [events](https://core.telegram.org/bots/webapps#events-available-for-mini-apps) activated, deactivated, safeAreaChanged, contentSafeAreaChanged, fullscreenChanged and fullscreenFailed for Mini Apps.

#### Homescreen Shortcuts

- [x] Mini Apps can now be accessed via [direct shortcuts](https://telegram.org/blog/fullscreen-miniapps-and-more#home-screen-shortcuts) added to the home screen of mobile devices.
- [x] Added the method addToHomeScreen to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps) to create a shortcut for users to add to their home screens.
- [x] Added the method checkHomeScreenStatus to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps) to determine the status and support of the home screen shortcut for the Mini App on the current device.
- [x] Added the [events](https://core.telegram.org/bots/webapps#events-available-for-mini-apps) homeScreenAdded and homeScreenChecked for Mini Apps.

#### Emoji Status

- [x] Mini Apps can now prompt users to set their [emoji status](https://telegram.org/blog/fullscreen-miniapps-and-more#emoji-status) - or request access to later sync it automatically with in-game badges, third-party APIs and more.
- [ ] Added the method [setUserEmojiStatus](https://core.telegram.org/bots/api#setuseremojistatus). The user must allow the bot to manage their emoji status. #4572 
- [x] Added the method setEmojiStatus to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps) to let users manually confirm a custom emoji as their new status via a native dialog.
- [x] Added the method requestEmojiStatusAccess to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps) for obtaining permission to later update a user's emoji status via the Bot API method [setUserEmojiStatus](https://core.telegram.org/bots/api#setuseremojistatus).
- [x] Added the [events](https://core.telegram.org/bots/webapps#events-available-for-mini-apps) emojiStatusSet, emojiStatusFailed and emojiStatusAccessRequested for Mini Apps.

#### Media Sharing and File Downloads

- [x] Users can now [share media](https://telegram.org/blog/fullscreen-miniapps-and-more#media-sharing) directly from Mini Apps - sending referral codes, custom memes, artwork and more to any chat or posting them [as a story](https://telegram.org/blog/w3-browser-mini-app-store#sharing-from-mini-apps-to-stories).
- [ ] Added the class [PreparedInlineMessage](https://core.telegram.org/bots/api#preparedinlinemessage) and the method [savePreparedInlineMessage](https://core.telegram.org/bots/api#savepreparedinlinemessage), allowing bots to suggest users to send a specific message from a Mini App via the method [shareMessage](https://core.telegram.org/bots/webapps#initializing-mini-apps). @Bibo-Joshi #4574 
- [x] Added the method shareMessage to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps) to share media from Mini Apps to Telegram chats.
- [x] Added the method downloadFile to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps), introducing support for a native popup that prompts users to download files from the Mini App.
- [x] Added the [events](https://core.telegram.org/bots/webapps#events-available-for-mini-apps) shareMessageSent, shareMessageFailed and fileDownloadRequested for Mini Apps.

#### Geolocation Access

- [x] Mini Apps can now request [geolocation access](https://telegram.org/blog/fullscreen-miniapps-and-more#geolocation-access) to users, allowing them to build virtually any location-based service, from games with dynamic points of interest to interactive maps for events.
- [x] Added the field LocationManager to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).
- [x] Added the [events](https://core.telegram.org/bots/webapps#events-available-for-mini-apps) locationManagerUpdated and locationRequested for Mini Apps.

#### Device Motion Tracking

- [x] Mini Apps can now track detailed [device motion data](https://telegram.org/blog/fullscreen-miniapps-and-more#device-motion-tracking), allowing them to implement better productivity tools, immersive VR experiences and more.
- [x] Added the fields isOrientationLocked, Accelerometer, DeviceOrientation and Gyroscope to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).
- [x] Added the methods lockOrientation and unlockOrientation to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps) to control the screen orientation.
- [x] Added the [events](https://core.telegram.org/bots/webapps#events-available-for-mini-apps) accelerometerStarted, accelerometerStopped, accelerometerChanged, accelerometerFailed, deviceOrientationStarted, deviceOrientationStopped, deviceOrientationChanged, deviceOrientationFailed, gyroscopeStarted, gyroscopeStopped, gyroscopeChanged, gyroscopeFailed for Mini Apps.

#### Gifts

- [x] Bots can now send [Paid Gifts](https://telegram.org/blog/gifts-verification-platform#gifts) to users in exchange for Telegram Stars.
- [ ] Added the classes [Gift](https://core.telegram.org/bots/api#gift) and [Gifts](https://core.telegram.org/bots/api#gifts) and the method [getAvailableGifts](https://core.telegram.org/bots/api#getavailablegifts), allowing bots to get all gifts available for sending. @Bibo-Joshi  #4576
- [ ] Added the method [sendGift](https://core.telegram.org/bots/api#sendgift), allowing bots to send gifts to users. @Bibo-Joshi  #4576
- [ ] Added the field gift to the class [TransactionPartnerUser](https://core.telegram.org/bots/api#transactionpartneruser). @Bibo-Joshi  #4576

#### Loading Screen Customization

- [x] Mini Apps can customize their loading screen, adding their own icon and specific colors for light and dark themes.
- [x] You can access these customization settings in [@BotFather](https://t.me/botfather) via /mybots > Select Bot > Bot Settings > Configure Mini App > Enable Mini App

#### Hardware-specific Optimizations

- [x] Mini Apps running on Android can now receive [basic information](https://core.telegram.org/bots/webapps#additional-data-in-user-agent) about a device's processing hardware, allowing them to optimize user experience based on the device's capabilities.
- [x] This information includes the OS, App and SDK's respective versions as well as the device's model and performance class.

#### General

- [x] Added the field photo_url to the class [WebAppUser](https://core.telegram.org/bots/webapps#webappuser) for all bots, allowing Mini Apps to access a user's profile photo if their privacy settings allow for it.
- [x] Third parties (e.g., Mini App builders) that receive or process data on behalf of Mini Apps are now able to [validate it](https://core.telegram.org/bots/webapps#validating-data-for-third-party-use) without knowing the App's [bot token](https://core.telegram.org/bots/tutorial#obtain-your-bot-token).
- [x] Debugging [options](https://core.telegram.org/bots/webapps#debug-mode-for-mini-apps) have been expanded to include full support for iOS devices. You can use these tools to find app-specific issues in your Mini App.
